Feature/open5gs k8s ue count
6G-SANDBOX/6G-Library pull request #66
Opened 2024-11-25 15:17 UTC by bjoern-r

Feature request to automaticallyprovision a varaible numer of UEs into the UDM of open5gs.
Same syntax as used in open5gs_vm component.

2024-11-25 15:18 UTC, bjoern-r commented
please test as berlin platform is currently on benchmark so i'm not 100% sure about the helm syntax and cannot deploy

2024-12-06 12:04 UTC, alvarocurt submitted a review, later dismissed
Look nice, but I found a potential problem for future deployments:
- mnc can be 2 or 3 digits, so we can't assume msin is always 10 digits long. An extra check must be done so that the msin is 9 or 10 digits long to not break the 15 digit requirement.

2024-12-06 13:56 UTC, bjoern-r commented
you are right, however the script before the change did also not take the mnc length into account.

2024-12-12 17:24 UTC, jmaciasportela requested changes

2024-12-12 17:24 UTC, jmaciasportela commented on open5gs/changelog.md
>  ### Changed
Please @bjoern-r increase the version number of the component into the changelog

2024-12-13 11:03 UTC, jmaciasportela approved these changes

2024-12-13 11:06 UTC, merged